[package]
name = "ugit-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.6", features = ["derive"] }
once_cell = "1.18.0"
sha1 = "0.10.6"
hex = "0.4.3"
